### ISSUE TITLE
Build and run python-based music box on ACOM machine

### ISSUE THREAD

**Issue by mattldawson** [NCAR/music-box#168]
blocked until Garth updates modeling2

**Comment by carl-drews** [comment]
This task is also tracked on the JIRA board for NRIT Web Engineering: https://jira.ucar.edu/browse/NRITW-596

**Comment by carl-drews** [comment]
MusicBox is successfully built on Carl's laptop running Windows:

C:\2024\MusicBox\music-box>pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing c:\2024\musicbox\music-box
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: musica==0.6.1.dev0 in c:\users\drews\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from acom_music_box==2.1.1) (0.6.1.dev0)
Building wheels for collected packages: acom_music_box
  Building wheel for acom_music_box (pyproject.toml) ... done
  Created wheel for acom_music_box: filename=acom_music_box-2.1.1-py2.py3-none-any.whl size=25499 sha256=0d8449b84c5f26a75326c9944791ee1fa2b98ad15a2972d2c2cbba7d60f10758
  Stored in directory: c:\users\drews\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local\pip\cache\wheels\7a\8b\12\baa7be9838129b2808942d004ec875ba886b8808fa89965878
Successfully built acom_music_box
Installing collected packages: acom_music_box
Successfully installed acom_music_box-2.1.1
C:\2024\MusicBox\music-box>

**Comment by K20shores** [comment]
It's up and running on multiple NCAR machines, or at least has been shown to
