### ISSUE TITLE
Discrepancy between local docker image & latest web calculations

### ISSUE THREAD

**Issue by kkowalsk** [NCAR/music-box#254]
There appears to be a mathematical error between docker image ` 1.1.1.` (downloaded last year) and the latest web version (Oct 7th, 24). 

Inputting the same concentrations and reactions between both models results in different results with the web version appearing to be inaccurate by an order of 10^3. 

NOx chemistry reaction:
* species
  * N2,  
  * O2, 
  * NO, 
  * NO2, 
  * O, 
  * O3
* Rxn
  * NO2 -> NO + O (photolysis)
    * MUSICA: NO2photo
    * Rxn Conditions: NO2photo = 0.01
  * O + O2 + M -> O3 + M (Arrhenius) 
    * A = 6e-34
  * NO + O3  ->  NO2 + O2
    * A = 1.8e-14
* concentrations
  * N2 = 2e19 molecules/cm3
  * O2 = 5e18 molecules/cm3
  * NO = 0
  * NO2 = 1e12 molecules/cm3 
  * O3 = 0

We are expecting this graph: 
![image](https://github.com/user-attachments/assets/3fa546ef-0679-41c6-85f2-f39429a8e5be)

But, those results only occur if the concentrations are bumped up by an order of 10^3 to: 
* concentrations
  * N2 = 2e22 molecules/cm3
  * O2 = 5e21 molecules/cm3
  * NO2 = 1e15 molecules/cm3

**Comment by K20shores** [comment]
Hi @kkowalsk! Thanks for the report!

The old version of musicbox used the [camp](https://github.com/open-atmos/camp) solver. We are now using our [musica](https://pypi.org/project/musica/) python package which uses the [micm](https://github.com/NCAR/micm) solver. All of music box has been rewritten so there may be some things that are wrong.

We'll look into this and see if we can figure out the discrepancy. Thanks for using music box!

**Comment by K20shores** [comment]
I believe this config file contains a configuration for this. Dropping it here so I don't lose it

[config.zip](https://github.com/user-attachments/files/17318551/config.zip)

**Comment by kkowalsk** [comment]
Hi @K20shores ,

I'm new to MusicBox, how should I configure this configuration file? We are using MusicBox in my class at CU Boulder.

**Comment by K20shores** [comment]
Hi @kkowalsk 

The attached configuration file recreates the simulation conditions you listed, assuming I didn't make any typos.

You can use it in two ways.

1. Run from the command line directly. The command line tool for musicbox is available from pypi with `pip install acom_music_box`. After you install that, a command line tool `music_box` should be available for you to use. You would unzip the configuration file, and then run it like this `music_box -c /Users/kshores/Downloads/configuration/my_config.json -o ~/Desktop/results.csv`. The command line tool can useful if you already have a configuration you want to run. We are also working to expand the python package so that you could define your simulation entirely in data in python and run simulations that way
3. Upload to the website. 
  - Go to [https://musicbox.acom.ucar.edu/](https://musicbox.acom.ucar.edu/)
  - Click on Get Started
  - Click on Upload configuration file
  - Choose File then Upload
<img width="1728" alt="Screenshot 2024-10-10 at 8 27 15 AM" src="https://github.com/user-attachments/assets/368fcf50-cfbf-4fef-9412-f8601071b931">


Hope that helps. In the meantime I'll continue investigating why the values appear to be incorrect.

**Comment by kkowalsk** [comment]
Oh, gotcha, thanks @K20shores. 

I didn't pay close enough attention - I thought maybe you had solved the issue, but you were just dropping the configuration that demonstrates the bug. 

I double checked the configuration - yes, that is how we replicated the issue.

**Comment by K20shores** [comment]
@kkowalsk I think we were converting from `mol cm-3` to `mol m-3` incorrectly, hence the factor of 10^3.

#255, which focues on other work, should also fix this. In particular, the changes to [this file](https://github.com/NCAR/music-box/pull/255/files#diff-411664080904b575f4c83e81a9589eb144c910b92d91c899256e13aebc721ef3) should fix things. 

I'll push a fix to the website on Monday morning and ping you when that's done. Thanks for reporting this!

**Comment by kkowalsk** [comment]
Ah, yup, that makes a lot of sense! 

Cool, thanks for the quick turn around on this!

**Comment by K20shores** [comment]
@kkowalsk of course! I've published a fixed; attached is a screenshot of a run of your mechanism on the website. Please let us know if you find anything else incorrect or any new features you may think of!

<img width="1728" alt="Screenshot 2024-10-13 at 2 15 13 PM" src="https://github.com/user-attachments/assets/aaa158ce-7738-4ab1-aff8-d3be816f43c5">
